apiVersion: v1
kind: Service
metadata:
  name: drupal-app1-service
spec:
  selector:
    app: drupal-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
