apiVersion: v1
kind: Service
metadata:
  name: drupal-app2-service
spec:
  selector:
    app: drupal-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
