apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-app2
  template:
    metadata:
      labels:
        app: drupal-app2
    spec:
      containers:
      - name: drupal-app2
        image: your-drupal-app2-image:tag
        ports:
        - containerPort: 80
        env:
        - name: COMMON_DATA
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: common_data
